# Generated by Django 4.2.29 on 2026-04-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(choices=[('bakery', 'Bakery'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('supermarket', 'Supermarket / Retail'), ('catering', 'Catering'), ('distributor', 'Distributor / Wholesaler'), ('other', 'Other')], default='other', max_length=20)),
                ('products_interested', models.TextField(blank=True, help_text='Products the prospect wants to sample.')),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('home_hero', 'Home Hero'), ('exit_popup', 'Exit Popup'), ('products_page', 'Products Page'), ('contact_page', 'Contact Page'), ('other', 'Other')], default='other', help_text='Which page or CTA captured this lead.', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('sent', 'Samples Sent'), ('converted', 'Converted to Customer'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
