# Generated by Django 4.2.29 on 2026-04-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerequest',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='source',
            field=models.CharField(choices=[('home_hero', 'Home Hero'), ('exit_popup', 'Exit Popup'), ('products_page', 'Products Page'), ('contact_page', 'Contact Page'), ('catalog_request', 'Catalog Request'), ('other', 'Other')], default='other', help_text='Which page or CTA captured this lead.', max_length=20),
        ),
    ]
