# Generated by Django 5.2.17 on 2026-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_samplerequest_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sales_notified',
            field=models.BooleanField(default=False, help_text='Whether the sales notification email was delivered to the SMTP server.'),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='sales_notified',
            field=models.BooleanField(default=False, help_text='Whether the sales notification email was delivered to the SMTP server.'),
        ),
    ]
