# Generated by Django 4.2.29 on 2026-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_sales_notified_samplerequest_sales_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='capi_sent',
            field=models.BooleanField(default=False, help_text='Whether the Conversions API accepted this lead.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='event_id',
            field=models.CharField(blank=True, help_text='Shared id that deduplicates the pixel and server copies of this conversion.', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='fbc',
            field=models.CharField(blank=True, help_text='Meta click id (_fbc cookie). Present only when the visitor arrived from an ad.', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='fbp',
            field=models.CharField(blank=True, help_text='Meta browser id (_fbp cookie).', max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='capi_sent',
            field=models.BooleanField(default=False, help_text='Whether the Conversions API accepted this lead.'),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='event_id',
            field=models.CharField(blank=True, help_text='Shared id that deduplicates the pixel and server copies of this conversion.', max_length=64),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='fbc',
            field=models.CharField(blank=True, help_text='Meta click id (_fbc cookie). Present only when the visitor arrived from an ad.', max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='fbp',
            field=models.CharField(blank=True, help_text='Meta browser id (_fbp cookie).', max_length=255),
        ),
    ]
