# Generated by Django 4.2.29 on 2026-10-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_capi_sent_lead_event_id_lead_fbc_lead_fbp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fbclid',
            field=models.CharField(blank=True, help_text='Meta click id from the ad URL. Also used to rebuild `fbc` when the pixel was blocked.', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, help_text='Google Ads click id.', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='landing_page',
            field=models.CharField(blank=True, help_text='First page of the visit that produced this lead.', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Whether the visitor had accepted marketing cookies when they submitted.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='referrer',
            field=models.CharField(blank=True, help_text='External page they arrived from.', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='fbclid',
            field=models.CharField(blank=True, help_text='Meta click id from the ad URL. Also used to rebuild `fbc` when the pixel was blocked.', max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='gclid',
            field=models.CharField(blank=True, help_text='Google Ads click id.', max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='landing_page',
            field=models.CharField(blank=True, help_text='First page of the visit that produced this lead.', max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Whether the visitor had accepted marketing cookies when they submitted.'),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='referrer',
            field=models.CharField(blank=True, help_text='External page they arrived from.', max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
