# Generated by Django 4.2.29 on 2026-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.CharField(blank=True, help_text='Business identification/registration number', max_length=50),
        ),
    ]
